server:
  port: 8080

logging:
  logging:
    org.springframework.web: DEBUG
    io.springbox.recommendations: DEBUG

spring:
  data:
    neo4j:
      driver: org.neo4j.ogm.drivers.http.driver.HttpDriver 
      uri: http://neo4j:7474
      username: neo4j
      password: secret
